### PR TITLE
Adds the possibility to select and unselect

### PR DESCRIPTION
**Pull request by MrSalametro**
I added buttons to the garage and cities view, to select and unselect all entries.

### CODE REVIEW

**Comment by LIPtoH** [comment]
In what case are these buttons needed? 
By default, I made it so that if no element is selected, then the actions are applied to all elements in the list. So you can buy all garages with one click and upgrade them to the maximum level in 2 clicks.

If you have other scenarios in mind please give an example. @MrSalametro

**Comment by MrSalametro** [comment]
I made it, because I wanted to select all garages, except three of them. So I had to click all the ones I wanted to be select and skip only three. Now I can select all and just deselect the three ones that I do not wanted to be selected.

If you don't think it makes sense, then the MR can be closed, I'm complete fine with that. I'll just save it as a patch and then apply it again.

**Comment by LIPtoH** [comment]
I see.
I'll take a look. Maybe i can add this before 1.49 with other tweaks and fixes.

**Comment by LIPtoH** [comment]
Implemented

**Pull request closed without merging**
